service: ${self:custom.secrets.SERVICE}

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true
  secrets: ${file(secrets.json)}

provider:
  name: aws
  logs:
    restApi: true
  runtime: nodejs16.x
  stage: staging
  environment:
    #postgresql
    POSTGRESQL_HOST: ${self:custom.secrets.MOCK_HOST}
    POSTGRESQL_PORT: ${self:custom.secrets.MOCK_PORT}
    DB_NAME: ${self:custom.secrets.MOCK_DB_NAME}
    MOCK_USER: ${self:custom.secrets.MOCK_USER}
    MOCK_PASSWORD: ${self:custom.secrets.MOCK_PASSWORD}

functions:
  # ADMIN
  # <<lamda file name in camel case>>:
  #   handler: src/<<provider ui tab name>>/<<lamda file name in camel case>>.handler
  #   events:
  #     - http:
  #         path: /<<lamda file name in all lowercase>>
  #         method: <<get OR post>>
  #         cors: true

